// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKvh6m0K2XA2UgUQidrsWk2DV1RJ6yJ_8',
    appId: '1:1007870535057:web:b4ec5f224f40443aaa2630',
    messagingSenderId: '1007870535057',
    projectId: 'flutter-firebase-integra-9f0f8',
    authDomain: 'flutter-firebase-integra-9f0f8.firebaseapp.com',
    storageBucket: 'flutter-firebase-integra-9f0f8.appspot.com',
    measurementId: 'G-2TT7J7E59N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhfyyFxjaRYZiHWgot7DaJ9mOeKBu7rlY',
    appId: '1:1007870535057:android:6f2019affb4eb883aa2630',
    messagingSenderId: '1007870535057',
    projectId: 'flutter-firebase-integra-9f0f8',
    storageBucket: 'flutter-firebase-integra-9f0f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwA9cxIPORWLTAUQJwn6owgud0dPG6kUE',
    appId: '1:1007870535057:ios:88a783bdb468c6a2aa2630',
    messagingSenderId: '1007870535057',
    projectId: 'flutter-firebase-integra-9f0f8',
    storageBucket: 'flutter-firebase-integra-9f0f8.appspot.com',
    iosClientId: '1007870535057-t4kmsqs2sfopo2ribeqjrikul5efgg6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwA9cxIPORWLTAUQJwn6owgud0dPG6kUE',
    appId: '1:1007870535057:ios:88a783bdb468c6a2aa2630',
    messagingSenderId: '1007870535057',
    projectId: 'flutter-firebase-integra-9f0f8',
    storageBucket: 'flutter-firebase-integra-9f0f8.appspot.com',
    iosClientId: '1007870535057-t4kmsqs2sfopo2ribeqjrikul5efgg6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
